name: Ne.app PDF CI (Develop)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build CI Pub - Install LaTeX (TexLive)
      run: sudo apt install texlive texlive-latex-extra texlive-latex-recommended
    - name: Build CI Pub - Test Makefile (Test)
      run: make all
    - name: Build CI Pub - Ack Note (Acknowledgments)
      run: make ack
